stringmatch/Controllers/StringMatchController.cs
using Microsoft.AspNetCore.Mvc;

namespace stringmatch.Controllers
{
    public class StringMatchController : Controller
    {
        public string? Title { get; set; }

        //Summary //
        //A function that retrieves data from and returns it to the app view UI.
        //Get: /StringMatch/
        
        public IActionResult Index(string phrase)
        {
            this.Title = "String Match Application";
            

            if (!String.IsNullOrEmpty(phrase))
            {
                List<string> result = StringMatcher(phrase);
                string[] data = result.ToArray();

                ViewData["a"] = data[0];
                ViewData["e"] = data[1];
                ViewData["i"] = data[2];
                ViewData["o"] = data[3];
                ViewData["u"] = data[4];
            }
            return View("Index");
        }
        //Summary//
        //A function that handles the string input and returns the indecies of all vowels in the string phrase. 
        //Get: /StringMatch/StringMatcher/
        public List<string> StringMatcher(string phrase)
        {
            var firstVowelPositions = new System.Text.StringBuilder();
            var secondVowelPositions = new System.Text.StringBuilder();
            var thirdVowelPositions = new System.Text.StringBuilder();
            var fourthVowelPositions = new System.Text.StringBuilder();
            var lastVowelPositions = new System.Text.StringBuilder();
            
            List<string> result = new();
            
            int pos = 0;
            
            foreach (char c in phrase)
            {
                if(c == 'a')
                {
                    firstVowelPositions = firstVowelPositions.Append(pos.ToString()+",");
                    pos++;
                }
                else if (c == 'e')
                {
                    secondVowelPositions = secondVowelPositions.Append(pos.ToString() + ",");
                    pos++;
                }
                else if (c == 'i')
                {
                    thirdVowelPositions = thirdVowelPositions.Append(pos.ToString() + ",");
                    pos++;
                }
                else if (c == 'o')
                {
                    fourthVowelPositions = fourthVowelPositions.Append(pos.ToString() + ",");
                    pos++;
                }
                else if (c == 'u')
                {
                    lastVowelPositions = lastVowelPositions.Append(pos.ToString() + ",");
                    pos++;
                }
                else
                {
                    pos++;
                    //Sanitize output and get it ready to be returned back to calling context.
                    if(pos == (phrase.Length))
                    {
                        string firstVpos = "No Matches";
                        string secondVpos = "No Matches";
                        string thirdVpos = "No Matches";
                        string fourthVpos = "No Matches";
                        string lastVpos = "No Matches";

                        if (firstVowelPositions.Length > 0)
                        {
                            firstVpos = firstVowelPositions.ToString().TrimEnd(',');
                        }
                        if(secondVowelPositions.Length > 0) {
                            secondVpos = secondVowelPositions.ToString().TrimEnd(',');
                        }
                        if(thirdVowelPositions.Length > 0) {
                            thirdVpos = thirdVowelPositions.ToString().TrimEnd(',');
                        }
                        if(fourthVowelPositions.Length > 0) {
                            fourthVpos = fourthVowelPositions.ToString().TrimEnd(',');
                        }
                        if(lastVowelPositions.Length > 0) {
                            lastVpos = lastVowelPositions.ToString().TrimEnd(',');
                        }

                        result.Add(firstVpos);
                        result.Add(secondVpos);
                        result.Add(thirdVpos);
                        result.Add(fourthVpos);
                        result.Add(lastVpos);
                    }
                }
                
            }
            return result;
        }
    }
}

stringmatch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]  - String-match Application</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/stringmatch.styles.css" asp-append-version="true" />
</head>
<body>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

stringmatch/Views/StringMatch/Index.cshtml
@{
    ViewData["Title"] = "Simple String Match Application";
}


<div class="container py-5 h-100">
<div class="row d-flex justify-content-center align-items-center h-100">
    <div class="col-xl-10">
    <div class="card rounded-3 text-black">
        <div class="row g-0">
        <div class="col-lg-6">
            <div class="card-body p-md-5 mx-md-4">

            <div class="text-center">
                <img class="img-fluid" src="~/images/logo.png"
                style="width: 185px;" alt="logo">
            </div>

            <form asp-controller="StringMatch" asp-action="Index" method="get">
                <p>Enter your preferred phrase below to see indecies for vowels in it</p>

                <div class="form-outline mb-4">
                <input type="text" name="phrase" id="phrase" class="form-control"
                    placeholder="Enter your phrase" />
                </div>

                <div class="text-center pt-1 mb-5 pb-1">
                <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="submit">Submit</button>
                </div>
            </form>

            </div>
        </div>
        <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
            <div class="text-white px-3 py-4 p-md-5 mx-md-4">
            <h3 class="mb-4">View your results below</h3>
            <p><strong>Your phrase:</strong> </p>
            <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">Vowels</th>
                      <th scope="col">Vowel Index Positions</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>a</td>
                      <td>@ViewData["a"]</td>
                    </tr>
                    <tr>
                      <td>e</td>
                       <td>@ViewData["e"]</td>
                    </tr>
                    <tr>
                      <td>i</td>
                       <td>@ViewData["i"]</td>
                    </tr>
                    <tr>
                      <td>o</td>
                       <td>@ViewData["o"]</td>
                    </tr>
                    <tr>
                      <td>u</td>
                       <td>@ViewData["u"]</td>
                    </tr>
                  </tbody>
                </table>
            </div>
        </div>
        </div>
    </div>
    </div>
</div>
</div>